# Workflow name
name: Movie Picture backend

#env:
#  REACT_APP_MOVIE_API_URL: http://localhost:5000  

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
      
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches: [main]
    types: [edited]

# Jobs defined in the workflow
jobs:


  backend_test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v4
      # Set up a python environment using the specified python version.
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install the dependencies.
      #- run: cd starter/backend && pipenv install
      #- run: cd starter/backend && pip install pipenv
      #- run: |
      #   python -m pip install --upgrade pip
      #   pip install pytest
      - run: |
          apk update && \
          apk add \
          pcre \
          pcre-dev \
          build-base \
          gcc \
          linux-headers \
          openssl \
          libffi-dev \
          && pip install pipenv

      # Run the tests.
      #- run: cd starter/backend && pipenv run test
      #- run: cd starter/backend && python test_app.py
      # pytest starter/backend/test_app.py
      - run: |
          ls 
          cd starter/backend 
          pytest test_app.py


