# Workflow name
name: Movie Picture frontend

env:
  REACT_APP_MOVIE_API_URL: http://localhost:5000  

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
      
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches: 
      - main
    paths:
      - 'starter/frontend/**'

# Jobs defined in the workflow
jobs:
  frontend_lint:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Check out the code from the repository.
        uses: actions/checkout@v4

      - name: Go to an application folder
        run: cd starter/frontend 

      - name: Set up a Node.js environment using the specified node version.
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - name: Install the dependencies.
        #run: cd starter/frontend && npm ci
        run: cd starter/frontend && npm install

      - name: Run the linter.
        run: cd starter/frontend && npm run lint

  frontend_test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Check out the code from the repository.
        uses: actions/checkout@v4

      - name: Go to an application folder
        run: cd starter/frontend 

      - name: Set up a Node.js environment using the specified node version.
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - name: Install the dependencies.
        #run: cd starter/frontend && npm ci
        run: cd starter/frontend && npm install

      - name: Run the tests.
        run: cd starter/frontend && CI=true npm test


  frontend_build:
    needs: [frontend_lint, frontend_test]
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v4

      # Build image.
      - run: cd starter/frontend && docker build --build-arg=REACT_APP_MOVIE_API_URL=${{env.REACT_APP_MOVIE_API_URL}} --tag=mp-frontend:latest .
